name: gwt_mail_sample
description: A Dart app that uses AngularDart
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0

dev_dependencies:
  build_web_compilers: ^0.4.4
  build_runner: ^1.1.1
