name: gwt_mail_sample
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=2.0.0-dev <2.0.0'
web:
  compiler:
    debug: dartdevc
dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
# Required to use AngularDart bleeding edge.
dependency_overrides:
  analyzer: ^0.31.0-alpha
  angular:
    git:
      url: https://github.com/dart-lang/angular
      path: angular
      ref: github-sync
  angular_compiler:
    git:
      url: https://github.com/dart-lang/angular
      path: angular_compiler
      ref: github-sync
  observable:
    git:
      url: https://github.com/dart-lang/observable
  quiver:
    git:
      url: https://github.com/google/quiver-dart
transformers:
- angular
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions:
      - --trust-type-annotations
      - --trust-primitives
      - --dump-info
