name: gwt_mail_sample
description: A Dart app that uses AngularDart
environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: 5.0.0-alpha+8
  angular_components: 0.9.0-alpha+8

dev_dependencies:
  # Currently broken with 0.3.4+2 - github.com/dart-lang/sdk/issues/32600
  build_web_compilers: 0.3.4+1
  build_runner: ^0.8.0
