name: gwt_mail_sample
description: A Dart app that uses AngularDart
environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: 5.0.0-alpha+11
  angular_components: 0.9.0-alpha+11

dev_dependencies:
  build_web_compilers: ^0.3.6
  build_runner: ^0.8.2
