name: gwt_mail_sample
description: A Dart app that uses AngularDart
environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: 5.0.0-alpha+7
  angular_components: 0.9.0-alpha+7

dev_dependencies:
  build_web_compilers: ^0.3.0
  build_runner: ^0.7.3
